export const MAKING_REQUEST = 'MAKING_REQUEST';
export const FINISHED_REQUEST = 'FINISHED_REQUEST';

export const LIST_TANKS = 'LIST_TANKS';
export const CREATE_TANK = 'CREATE_TANK';
export const RETRIEVE_TANK = 'RETRIEVE_TANK';
export const UPDATE_TANK = 'UPDATE_TANK';
export const DELETE_TANK = 'DELETE_TANK';
export const BOOST_TANK = 'BOOST_TANK';

export const LIST_BOOSTS = 'LIST_BOOSTS';
export const CREATE_BOOST = 'CREATE_BOOST';
export const RETRIEVE_BOOST = 'RETRIEVE_BOOST';
export const UPDATE_BOOST = 'UPDATE_BOOST';
export const DELETE_BOOST = 'DELETE_BOOST';

export const LIST_ACTIVITIES = 'LIST_ACTIVITIES';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const RETRIEVE_ACTIVITY = 'RETRIEVE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
